#!/usr/bin/env python3
"""Decode deterministic campaign PCAP frames into readable trace lines."""

import argparse
import struct
from pathlib import Path


def decode_packets(raw: bytes) -> list[str]:
    if len(raw) < 24:
        raise ValueError("pcap too short")

    offset = 24
    lines: list[str] = []
    index = 1

    while offset + 16 <= len(raw):
        ts_sec, ts_usec, incl_len, _orig_len = struct.unpack_from("<IIII", raw, offset)
        offset += 16
        if offset + incl_len > len(raw):
            break

        frame = raw[offset : offset + incl_len]
        offset += incl_len

        if len(frame) < 14 + 20 + 20:
            continue

        eth_type = struct.unpack_from("!H", frame, 12)[0]
        if eth_type != 0x0800:
            continue

        ip_header = frame[14:34]
        ihl = (ip_header[0] & 0x0F) * 4
        proto = ip_header[9]
        if proto != 6:
            continue

        src_ip = ".".join(str(b) for b in ip_header[12:16])
        dst_ip = ".".join(str(b) for b in ip_header[16:20])

        tcp_start = 14 + ihl
        sport, dport = struct.unpack_from("!HH", frame, tcp_start)
        data_offset = ((frame[tcp_start + 12] >> 4) & 0x0F) * 4
        payload_start = tcp_start + data_offset
        payload = frame[payload_start:]
        payload_text = payload.decode("utf-8", errors="replace")

        lines.append(
            f"{index:02d} ts={ts_sec}.{ts_usec:06d} {src_ip}:{sport} -> {dst_ip}:{dport} payload={payload_text}"
        )
        index += 1

    return lines


def main() -> None:
    parser = argparse.ArgumentParser(description="Decode deterministic AMHS campaign PCAP")
    parser.add_argument("pcap", help="Path to .pcap file generated by campaign scripts")
    args = parser.parse_args()

    path = Path(args.pcap)
    data = path.read_bytes()
    lines = decode_packets(data)
    print(f"decoded_file={path}")
    print(f"packet_count={len(lines)}")
    for line in lines:
        print(line)


if __name__ == "__main__":
    main()
